application: dilingkari
version: 1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  WEB_INSTANCE: 'di.lingkari.com'
  DB_INSTANCE: 'dilingkari.appspot.com'
  API_INSTANCE: 'dilingkari.appspot.com'

handlers:
- url: /(.*\.(gif|png|jpg|ico))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico)$
- url: /p
  script: api_profile.app
- url: /p/.*
  script: api_profile.app
- url: /a
  script: api_activity.app
- url: /a/.*
  script: api_activity.app
- url: /indonesia
  script: db_indonesia.app
- url: /count_indonesia
  script: db_indonesia.app
- url: /cron_indonesia
  script: db_cron_indonesia.app
- url: /profile
  script: db_profile.app
- url: /profile/.*
  script: web_dilingkari.app
- url: .*
  script: web_dilingkari.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
