application: dilingkari
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: dilingkari.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
